# Generated by Django 3.0.4 on 2020-11-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidatedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technology', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('Job_Location', models.CharField(max_length=100)),
                ('Passed_out', models.CharField(max_length=10)),
                ('expected_monthly_salary', models.CharField(max_length=10)),
                ('Past_company', models.CharField(max_length=20)),
                ('Reference', models.CharField(max_length=50)),
                ('course_fees', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
    ]
